# Generated by Django 5.0.6 on 2024-06-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=50)),
                ('work_type', models.CharField(choices=[('Roof', 'Roof'), ('Kitchen', 'Kitchen'), ('Doors', 'Doors'), ('Floors', 'Floors'), ('Skirtings', 'Skirtings'), ('Other', 'Other')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_page', models.BooleanField(default=False)),
                ('portfolio_page', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
