# Generated by Django 5.0.6 on 2024-06-16 15:06

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[images.models.validate_image]),
        ),
    ]
